"""Descrição da migração

Revision ID: 4af71fc4b5f4
Revises: 
Create Date: 2023-05-23 01:41:53.298851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af71fc4b5f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_total_aulas', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplina', schema=None) as batch_op:
        batch_op.drop_column('quantidade_total_aulas')

    # ### end Alembic commands ###
